server:
    port: 2200
spring:
    application:
        name: eureka
eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:${server.port}/eureka/
        register-with-eureka: false
        fetch-registry: false
security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123